### PR TITLE
Works a minor mode, add some motions...

### PR DESCRIPTION
**Pull request by linktohack**

### CODE REVIEW

**Comment by alexmurray** [comment]
Thanks - on the surface looks okay but I would like if can you elaborate on the advantages of these changes? In particular why motion change to motion mode and why make it a minor mode?

Can you also please update the `README.md` to include instructions for enabling it now since if it is a minor mode a simple `(require 'evil-vimish-fold)` is not enough anymore and instead there also needs to be an `(evil-vimish-fold-mode 1)`

**Comment by linktohack** [comment]
To answer your questions:
- Make it a minor mode allow user to rollback to `evil`'s default behaviour without restarting emacs.
- Some modes start in motion state (e.g. Help mode, Info mode)
- README updated.

**Comment by linktohack** [comment]
Ok, typos fixed :)

**Comment by alexmurray** [comment]
Thanks.

**Pull request merged**
